on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin, freebsd, openbsd, netbsd]
        goarch: [386, amd64, arm, arm64, riscv64]
        exclude:
          # Exclude unsupported combinations
          - goarch: 386
            goos: darwin
          - goarch: arm
            goos: darwin
          - goarch: arm64
            goos: windows
          - goarch: arm
            goos: windows
          - goarch: riscv64
            goos: windows
          - goarch: riscv64
            goos: darwin
          - goarch: arm
            goos: openbsd
          - goarch: arm64
            goos: openbsd
          - goarch: riscv64
            goos: openbsd
          - goarch: arm
            goos: netbsd
          - goarch: arm64
            goos: netbsd
          - goarch: riscv64
            goos: netbsd
    steps:
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}